export {
  buildHeuristicMultilingualSuggestions,
  detectWrongLanguagePresentation,
  governedAliasSeedsFromSource,
  GOVERNED_MULTILINGUAL_DISCLAIMER,
  GOVERNED_MULTILINGUAL_PROMPT_VERSION,
  PENDING_HINDI_DESCRIPTION_MARKER,
  PENDING_SELLING_POINT_MARKER,
  resolveLocale,
  resolveSellingPointForLocale,
  resolveTemplateHindiDescription,
  serializeMultilingualSuggestions,
  validateGovernedHindiDescription,
  validateMultilingualSource,
  validateMultilingualText,
  validateProviderMultilingualEnvelope,
} from "./governedMultilingualContract";
export {
  buildAuthoritativeMultilingualSource,
  type MockMultilingualScenario,
  mockMultilingualProvider,
} from "./governedMultilingualProvider";
export {
  MULTILINGUAL_LOCALE_SCRIPTS,
  SUPPORTED_MULTILINGUAL_LOCALES,
  type AuthoritativeMultilingualSource,
  type GovernedMultilingualFieldSuggestion,
  type GovernedMultilingualProvenance,
  type GovernedMultilingualSuggestionResult,
  type LocaleResolutionResult,
  type MultilingualAvailability,
  type MultilingualLocaleCode,
  type MultilingualReviewStatus,
  type MultilingualSuggestionKind,
} from "./types";
