import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Printer, ArrowLeft, MessageCircle, Copy } from "lucide-react";
import { toast } from "sonner";

const DEFAULTS = {
  validity: "Prices are indicative and subject to final confirmation at the time of order.",
  tax: "GST, transport, customization, and packaging charges may apply as per final invoice.",
  transport: "Transport / freight quoted separately based on destination and order size.",
  customization: "Customization must be confirmed in writing before production. Changes after approval may affect cost, timeline, and dispatch date.",
  footer: "Oasis Baklawa · Premium Arabic & Indo-Arabic Gourmet Sweets · Catalogue generated by Oasis Catalogue AI Studio",
};

const HIDDEN_CHANNELS = new Set(["franchisee", "own_outlet", "special_customer"]);

const CatalogueProposal = () => {
  const { id } = useParams();
  const nav = useNavigate();
  const [cat, setCat] = useState<any>(null);
  const [items, setItems] = useState<any[]>([]);
  const [chMap, setChMap] = useState<Record<string, any>>({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data: c } = await supabase.from("catalogues").select("*").eq("id", id).maybeSingle();
      if (!c) { setLoading(false); return; }
      setCat(c);
      const { data: cp } = await supabase.from("catalogue_products").select("*, products(*)").eq("catalogue_id", id).order("sort_order");
      setItems(cp ?? []);
      if (c.public_slug) {
        const { data: rpc } = await supabase.rpc("get_public_catalogue_channel_data", { _slug: c.public_slug });
        const m: Record<string, any> = {};
        (rpc ?? []).forEach((r: any) => { m[r.product_id] = r; });
        setChMap(m);
      }
      setLoading(false);
    })();
  }, [id]);

  if (loading) return <div className="min-h-screen flex items-center justify-center text-muted-foreground">Loading proposal…</div>;
  if (!cat) return <div className="min-h-screen flex items-center justify-center text-muted-foreground">Catalogue not found.</div>;

  const channel: string = cat.target_customer_channel ?? "price_hidden";
  const channelSafe = !HIDDEN_CHANNELS.has(channel);
  const showPrice = !!cat.show_price && channel !== "price_hidden" && channelSafe;
  const showMrp = !!cat.show_mrp;
  const showDiscount = !!cat.show_discount;
  const priceLabel = cat.show_price_label || (channel !== "price_hidden" ? channel.replace(/_/g, " ") + " price" : "Price");

  const renderPrice = (p: any) => {
    if (!channelSafe) return <div className="text-sm italic text-muted-foreground mt-2">Price on request</div>;
    const r = chMap[p.id];
    if (showPrice && r?.public_price != null) {
      return (
        <div className="mt-2">
          <div className="font-display text-lg" style={{ color: "hsl(var(--accent))" }}>
            {r.currency || "₹"} {r.public_price}
            <span className="text-[10px] uppercase tracking-wider ml-2 text-muted-foreground">{r.price_label || priceLabel}</span>
            {showDiscount && r.discount_percent ? <span className="text-[10px] ml-2 text-success">-{r.discount_percent}%</span> : null}
          </div>
          {showMrp && r.mrp && <div className="text-[11px] text-muted-foreground line-through">MRP ₹ {r.mrp}</div>}
        </div>
      );
    }
    if (showMrp && (r?.mrp ?? p.mrp)) {
      return <div className="mt-2 font-display text-lg" style={{ color: "hsl(var(--accent))" }}>₹ {r?.mrp ?? p.mrp} <span className="text-[10px] uppercase ml-1 text-muted-foreground">MRP</span></div>;
    }
    return <div className="mt-2 text-sm italic text-muted-foreground">{r?.price_display_text || "Price on request"}</div>;
  };

  const renderMoq = (p: any) => {
    const r = chMap[p.id];
    return r?.moq_display_text || "MOQ depends on order type. Contact sales for details.";
  };

  const proposalDate = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const validityNote = cat.proposal_validity_note || DEFAULTS.validity;
  const taxNote = cat.proposal_tax_note || DEFAULTS.tax;
  const transportNote = cat.proposal_transport_note || DEFAULTS.transport;
  const customizationNote = cat.proposal_customization_note || DEFAULTS.customization;
  const footerNote = cat.proposal_footer_note || DEFAULTS.footer;
  const waMessage = cat.proposal_whatsapp_message || `Hello, please find the Oasis Baklawa proposal for ${cat.title}. Prices/MOQ are indicative and subject to final confirmation. Please reply here for order confirmation or customization.`;

  const copyMsg = () => { navigator.clipboard.writeText(waMessage); toast.success("Proposal message copied"); };

  return (
    <div className="min-h-screen bg-background">
      {/* Toolbar — hidden in print */}
      <div className="no-print sticky top-0 z-30 bg-card border-b">
        <div className="max-w-5xl mx-auto px-4 py-3 flex flex-wrap gap-2 items-center">
          <Button size="sm" variant="ghost" onClick={() => nav(`/catalogues/${id}`)}><ArrowLeft className="h-4 w-4 mr-1" />Back</Button>
          <div className="flex-1" />
          <Button size="sm" variant="outline" onClick={copyMsg}><Copy className="h-4 w-4 mr-1" />Copy WhatsApp message</Button>
          <Button size="sm" variant="outline" asChild><a href={`https://wa.me/?text=${encodeURIComponent(waMessage)}`} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4 mr-1" />Open WhatsApp</a></Button>
          <Button size="sm" onClick={() => window.print()}><Printer className="h-4 w-4 mr-1" />Print / Save PDF</Button>
        </div>
      </div>

      <div className="proposal-doc max-w-5xl mx-auto px-6 py-10 print-page">
        {/* Header */}
        <header className="border-b pb-6 mb-8" style={{ borderColor: "hsl(var(--accent) / 0.4)" }}>
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <div className="text-[10px] uppercase tracking-[0.3em] text-muted-foreground">Oasis Baklawa</div>
              <h1 className="font-display text-4xl mt-2" style={{ color: "hsl(var(--primary))" }}>{cat.title}</h1>
              {cat.subtitle && <div className="text-sm text-muted-foreground mt-1">{cat.subtitle}</div>}
            </div>
            <div className="text-right text-xs text-muted-foreground">
              <div><strong className="text-foreground">Proposal date:</strong> {proposalDate}</div>
              {cat.client_name && <div className="mt-1"><strong className="text-foreground">For:</strong> {cat.client_name}</div>}
              <div className="mt-1 capitalize"><strong className="text-foreground">Channel:</strong> {channel.replace(/_/g, " ")}</div>
            </div>
          </div>
          {cat.intro_text && <p className="text-sm mt-5 max-w-3xl leading-relaxed">{cat.intro_text}</p>}
        </header>

        {/* Products */}
        <section className="proposal-grid">
          {items.map(({ products: p }) => p && (
            <article key={p.id} className="proposal-card luxe-card flex flex-col">
              <div className="luxe-media relative">
                {p.hero_image_url && !p.hero_image_url.includes("/_pdf_pages/")
                  ? <img src={p.hero_image_url} alt={p.product_name} loading="lazy" />
                  : <div className="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-secondary to-accent-soft/40"><span className="font-display text-4xl text-accent/30">{p.product_name?.[0] ?? "·"}</span></div>}
              </div>
              <div className="p-5 flex-1 flex flex-col text-center">
                <div className="luxe-sub mb-2 truncate">{p.category || "Oasis Baklawa"}</div>
                <h3 className="luxe-title mb-2 break-words">{p.product_name}</h3>
                <div className="text-[10px] font-mono text-muted-foreground">{p.sku}</div>
                {p.short_description && <p className="text-xs mt-3 text-muted-foreground line-clamp-2">{p.short_description}</p>}
                <div className="text-[11px] mt-3 space-y-0.5 text-muted-foreground mt-auto">
                  {p.pack_size && <div>Pack · {p.pack_size}</div>}
                  {p.shelf_life_days && <div>Shelf life · {p.shelf_life_days} days</div>}
                  <div>{renderMoq(p)}</div>
                </div>
                <div className="mt-3 pt-3 border-t border-border/60">{renderPrice(p)}</div>
              </div>
            </article>
          ))}
        </section>

        {items.length === 0 && <div className="text-center text-muted-foreground py-8">No products in this catalogue.</div>}

        {/* Commercial summary */}
        <section className="mt-10 border-t pt-6 text-sm space-y-2" style={{ borderColor: "hsl(var(--accent) / 0.4)" }}>
          <h2 className="font-display text-xl mb-3" style={{ color: "hsl(var(--primary))" }}>Commercial notes</h2>
          <div><strong>Validity:</strong> {validityNote}</div>
          <div><strong>Tax:</strong> {taxNote}</div>
          <div><strong>Transport:</strong> {transportNote}</div>
          <div><strong>Customization:</strong> {customizationNote}</div>
        </section>

        {/* Footer */}
        <footer className="mt-10 pt-6 border-t text-center text-xs text-muted-foreground">
          {footerNote}
        </footer>
      </div>

      <style>{`
        .proposal-grid { display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 16px; }
        @media (max-width: 640px) { .proposal-grid { grid-template-columns: 1fr; } }
        @media print {
          .proposal-grid { grid-template-columns: repeat(2, minmax(0,1fr)); gap: 12px; }
          .proposal-card { break-inside: avoid; page-break-inside: avoid; }
          .proposal-doc { padding: 0 !important; }
          aside, nav, header.app-header { display: none !important; }
        }
      `}</style>
    </div>
  );
};

export default CatalogueProposal;
